### ISSUE TITLE
12V Support

### ISSUE THREAD

**Issue by xrtze** [lizardsystems/yawl-controller#20]
The NCP1117LPST33T3G supports up to 18V input... am I right to assume, that the yawl would work fine with 12V like WS2815?

**Comment by vzagorovskiy** [comment]
No it won't work.
 You need the signal to be 5V, but it will also be 12V. But there will be no signal because the level converter will burn out. The level converter has a maximum voltage of 5V.
You need to use a DC-DC converter as shown in the figure below. 

![изображение](https://github.com/lizardsystems/yawl-controller/assets/4923679/2173a58d-8c2d-4646-a93a-00b80a9ce866)
